development:
  cloud_name: ENV["MY_CLOUD_NAME"]
  api_key: ENV["MY_API_KEY"]
  api_secret: ENV["MY_SECRET_KEY"]


production:
  cloud_name: ENV["MY_CLOUD_NAME"]
  api_key: ENV["MY_API_KEY"]
  api_secret: ENV["MY_SECRET_KEY"]
